name: Update Translation Progress

on:
  push:
    paths:
      - "eng/**"
      - "it/**"
      - ".github/workflows/update-progress.yml"
      - "update_progress.py"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run script to update README
        run: python3 update_progress.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_GITHUB }}
          commit-message: "chore: update translation progress"
          branch: update/progress
          title: "Aggiornamento percentuale traduzione"
          body: "Questo PR aggiorna la percentuale di traduzione in README.md"
